import { UserProvider } from '@/components/context/authContext'
import './globals.css'



export const metadata = {
  title: 'RealChat App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <link rel="icon" href="/" sizes="any" />
          {children}
        </body>
      </UserProvider>
    </html>
  )
}
